package com.mycompany.expensestracker;

/**
 *
 * @author Ayesha
 */
public class ExpenseCard extends javax.swing.JPanel {

    /**
     * Creates new form ExpenseCard
     */
    public ExpenseCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGalaName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        scrollAmbag = new javax.swing.JScrollPane();
        txtAmbagDisplay = new javax.swing.JTextArea();
        lblPrice = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));

        lblGalaName.setText("Title");

        lblDate.setText("Date");

        txtAmbagDisplay.setColumns(20);
        txtAmbagDisplay.setRows(5);
        scrollAmbag.setViewportView(txtAmbagDisplay);

        lblPrice.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addComponent(scrollAmbag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblGalaName)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblGalaName)
                .addGap(16, 16, 16)
                .addComponent(scrollAmbag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDate)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGalaName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JScrollPane scrollAmbag;
    private javax.swing.JTextArea txtAmbagDisplay;
    // End of variables declaration//GEN-END:variables

    public void setCardData(String galaName, String date, String price, String ambagList) {
    // Replace these names with whatever you named your labels in Design view
    lblGalaName.setText(galaName); 
    lblDate.setText(date);
    lblPrice.setText("₱" + price);
    
    // This puts the list of friends/ambag into your JTextArea or Label
    txtAmbagDisplay.setText(ambagList); 
    }
    
}
